/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mini.calculator;

import mini.calculator.controllers.Main;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.stage.Stage;
import javafx.scene.Scene;
import javafx.scene.image.*;
import javafx.fxml.FXML;

public class App extends Application {

  @Override
  public void start (Stage stage) throws Exception {

    Main root = new Main ();

    Scene scene = new Scene (root, 305, 450);
    stage.setScene (scene);
    stage.setMinWidth (305);
    stage.setMaxWidth (305);
    stage.setMinHeight (450);
    stage.setMaxHeight(450);
    stage.setTitle ("Mini-Calculator");
    stage.getIcons().add(new Image ("/icon.png"));
    stage.show ();

  }


  public static void main (String[] args) {
    Application.launch (args);
  }

}