/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mini.calculator;

import org.junit.Test;
import static org.junit.Assert.*;

import mini.calculator.logic.Evaluator;

public class AppTest {
    // @Test public void testAppHasAGreeting() {
    //     App classUnderTest = new App();
    //     assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    // }

    // @Test public void testEvaluator () {
    //     Evaluator cls = new Evaluator ();

    //     assertNotNull ("(java)", cls.trial());
    // }
}
